apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-deployment
  namespace: honda
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: arbusermanagement
        image: registry.k8s/arbusermanagement:IMG_ID
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
        ports:
        - containerPort: 80